services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: platform_admin_security
      POSTGRES_USER: telcosuite
      POSTGRES_PASSWORD: telcosuite
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
